language: java

sudo: required

services:
  - docker

python:
  - "3.4"

before_install:
  - sudo apt-get update
  - sudo apt-get -y install python3-pip python-dev
  - python3 -V
  - pip3 -V
  - sudo bash py-test/travis-fix.sh

install:
  - sudo pip3 install requests_toolbelt

jdk:
  - oraclejdk9

script:
  - docker-compose down
  - ./gradlew check dist
  - docker-compose up -d --build
  - ./gradlew ws:run --stacktrace &
  - sleep 30 && python3 py-test/request.py

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/