version: '2'

services:
  zoo1:
    image: 'bitnami/zookeeper:latest'
    hostname: zoo1
    environment:
    - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
    - ./docker-config/zoo1:/bitnami/zookeeper

  kafka1:
    image: 'bitnami/kafka:latest'
    hostname: kafka1
    environment:
    - KAFKA_ZOOKEEPER_CONNECT=zoo1:2181
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://:9092
    - KAFKA_LISTENERS=PLAINTEXT://:9092
    - KAFKA_ADVERTISED_HOST_NAME=kafka1
    - KAFKA_ADVERTISED_PORT=9092
    depends_on:
    - zoo1
    volumes:
    - ./docker-config/kafka1:/bitnami/kafka

  mysql1:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: twRuvi2ejllDdA4nnQLa08O
      MYSQL_DATABASE: submissionchecker
    volumes:
    - ./docker-config/mysql1:/var/lib/mysql
  bash1:
    image: bash:4.4
  mysql2:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SqfyBWhiFGr7FK60cVR2rel
    volumes:
    - ./docker-config/mysql2:/var/lib/mysql
  ws:
    image: bees4ever/ws:v0.0.11
    depends_on:
    - mysql1
    - kafka1
    - zoo1
    ports:
    - "443:8080"
    volumes:
    - ./ws/upload-dir:/upload-dir
    - ./ws/zip-dir:/zip-dir
    - ./docker-config/ws/application_prod.properties:/usr/local/appconfig/application.properties
    - ./docker-config/ws/markdown/:/usr/local/appconfig/markdown/
  secrettokenchecker:
    image: bees4ever/secrettokenchecker:v0.0.11
    depends_on:
    - mysql1
    - kafka1
    - zoo1
    - ws
    environment:
      HOST_UPLOAD_DIR: "${PWD}/secrettoken-checker/upload-dir"
    volumes:
    - /var/run/:/var/run/
    - /var/run/docker.sock:/var/run/docker.sock
    - ./secrettoken-checker/upload-dir:/upload-dir
    - ./docker-config/secrettoken/application_prod.conf:/usr/local/appconfig/application.config
  sqlchecker:
    image: bees4ever/sqlchecker:v0.0.11
    depends_on:
    - mysql2
    - kafka1
    - zoo1
    - ws
    volumes:
    - ./sql-checker/upload-dir:/upload-dir
    - ./docker-config/sqlchecker/application_prod.conf:/usr/local/appconfig/application.config
