version: '2.1'

services:
  zoo1:
    image: 'bitnami/zookeeper:latest'
    hostname: zoo1
    environment:
        - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./docker-config/zoo1:/bitnami/zookeeper

  kafka1:
    image: 'bitnami/kafka:latest'
    environment:
    - KAFKA_ZOOKEEPER_CONNECT=zoo1:2181
    - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
    - zoo1
    volumes:
      - ./docker-config/kafka1:/bitnami/kafka
      #- /var/run/docker.sock:/var/run/docker.sock

  mysql1:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: twRuvi2ejllDdA4nnQLa08O
      MYSQL_DATABASE: submissionchecker
    volumes:
      - ./docker-config/mysql1:/var/lib/mysql

  bash1:
    image: bash:4.4
  mysql2:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SqfyBWhiFGr7FK60cVR2rel
    volumes:
      - ./docker-config/mysql2:/var/lib/mysql

  ws:
    build: ws
    #container_name: ws
    image: ws
    depends_on:
      - mysql1
      - kafka1
      - zoo1
    ports:
      - "443:8080"
    volumes:
      - ./ws/upload-dir:/upload-dir
      - ./ws/zip-dir:/zip-dir
      - ./docker-config/ws/application.properties:/usr/local/appconfig/application.properties

  secrettokenchecker:
    build: secrettoken-checker
    #container_name: ws
    image: secrettokenchecker
    depends_on:
      - mysql1
      - kafka1
      - zoo1
    volumes:
      - ./docker-config/secrettoken/application.conf:/usr/local/appconfig/application.config
      - /var/run/:/var/run/
      - /var/run/docker.sock:/var/run/docker.sock
    #- ./secrettoken-checker/upload-dir:/upload-dir

  sqlchecker:
    #image: bees4ever/sqlchecker
    build: sql-checker
    depends_on:
    - mysql2
    - kafka1
    - zoo1
    - ws
    volumes:
    #- ./sql-checker/upload-dir:/upload-dir
    - ./docker-config/sqlchecker/application.conf:/usr/local/appconfig/application.config
